import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import Providers from './providers';
import Header from "@/components/ui/header";
import { SessionProvider } from 'next-auth/react';
import GoogleSignInScript from './GoogleSignInScript';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div style={{ flexGrow: 1 }}>
        {/* <SessionProvider>
          {children}
        </SessionProvider> */}
        {children}
        <GoogleSignInScript />
        </div>

      </body>
    </html>
  );
}
